In [1]:
#import sys
#!{sys.executable} -m pip install numpy

In [2]:
#import numpy as np
#print(np.__version__)

In [1]:
import numpy as np
from itertools import combinations
from math import comb

In [2]:
def model(z):
    return z[0]**8 + z[1] * z[2]

In [3]:
def finitechanges(x, x1, model=None):
    x = np.asarray(x, dtype=float).reshape(-1)
    x1 = np.asarray(x1, dtype=float).reshape(-1)

    dx = x1 - x
    n = len(x)
    m = 2 ** n

    U = np.zeros((n, m), dtype=float)

    col = 0

    # Columns for combinations of size 1, ..., n
    for l in range(1, n + 1):
        for combo in combinations(range(n), l):
            U[list(combo), col] = 1.0
            col += 1

    # Final column is the base case
    U[:, -1] = 0.0

    DX = x[:, None] + dx[:, None] * U

    if model is None:
        y = np.prod(DX, axis=0)
    else:
        y = np.array([model(DX[:, i]) for i in range(m)], dtype=float)

    ff = np.zeros(m, dtype=float)

    k = 0
    for l in range(1, n + 1):
        b = comb(n, l)

        for i in range(k, k + b):
            ff[i] = y[i]

            for u in range(k):
                is_subset = np.dot(U[:, i], U[:, u]) == np.sum(U[:, u])
                if is_subset:
                    ff[i] -= ff[u]

            ff[i] -= y[-1]

        k += b

    phi = U @ ff

    return k, U, DX, y, ff, phi

In [6]:
x = [1, 1, 1]
x1 = [2, 2, 2]

k, U, DX, y, ff, phi = finitechanges(x, x1)

print("k =", k)
print("U =\n", U)
print("DX =\n", DX)
print("y =", y)
print("ff =", ff)
print("phi =", phi)

k = 7
U =
 [[1. 0. 0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1. 1. 1. 0.]]
DX =
 [[2. 1. 1. 2. 2. 1. 2. 1.]
 [1. 2. 1. 2. 1. 2. 2. 1.]
 [1. 1. 2. 1. 2. 2. 2. 1.]]
y = [2. 2. 2. 4. 4. 4. 8. 1.]
ff = [1. 1. 1. 1. 1. 1. 1. 0.]
phi = [4. 4. 4.]
